# Generated by Django 3.2.7 on 2021-09-08 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210907_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47e1e3be-9da2-4983-bf9b-2c3e0e2a6bbb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
